#!/usr/bin/python3

def get_district_code_from_passing(passing):
	dists = {
	"MH01" : "Mumbai",
	"MH02" : "Mumbai",
	"MH03" : "Mumbai",
	"MH04" : "Thane",
	"MH06" : "Raigad",
	"MH07" : "Sindhudurg",
	"MH08" : "Ratnagiri",
	"MH09" : "Kolhapur",
	"MH10" : "Sangli",
	"MH11" : "Satara",
	"MH12" : "Pune",
	"MH13" : "Solapur",
	"MH14" : "Pimpri",
	"MH15" : "Nashik",
	"MH16" : "Ahmednagar",
	"MH17" : "Shrirampur",
	"MH18" : "Dhule",
	"MH19" : "Jalgaon",
	"MH20" : "Aurangabad",
	"MH21" : "Jalna",
	"MH22" : "Parbhani",
	"MH23" : "Beed",
	"MH24" : "Latur",
	"MH25" : "Osmanabad",
	"MH26" : "Nanded",
	"MH27" : "Amravati",
	"MH28" : "Buldana",
	"MH29" : "Yavatmal",
	"MH30" : "Akola",
	"MH31" : "Nagpur",
	"MH32" : "Wardha",
	"MH33" : "Gadchiroli",
	"MH34" : "Chandrapur",
	"MH35" : "Gondia",
	"MH36" : "Bhandara",
	"MH37" : "Washim",
	"MH38" : "Hingoli",
	"MH39" : "Nandurbar",
	"MH40" : "Nagpur",
	"MH41" : "Malegaon",
	"MH43" : "Mumbai",
	"MH44" : "Beed",
	"MH45" : "Solapur",
	"MH46" : "Khopoli",
	"MH47" : "Mumbai",
	"MH48" : "Palghar",
	"MH49" : "Nagpur",
	"MH50" : "Satara",
	"MH51" : "Nashik",
	"UT01" : "Almora",
	"UT11" : "Chamoli",
	"UT02" : "Bageshwar",
	"UT12" : "Pauri",
	"UT03" : "Champawat",
	"UT13" : "Rudraprayag",
	"UT04" : "Nanital",
	"UT14" : "Rishikesh",
	"UT05" : "Pithoragarh",
	"UT15" : "Kotdwar",
	"UT06" : "Udham Singh Nagar",
	"UT16" : "Vikasnagar",
	"UT07" : "Dehradun",
	"UT17" : "Roorkee",
	"UT08" : "Haridwar",
	"UT18" : "Kashipur",
	"UT09" : "Tehri",
	"UT19" : "Ramnagar",
	"UT10" : "Uttarkashi",
	"UT20" : "Ranikhet",
	"AP02" : "Anantapur",
	"AP03" : "Chittoor",
	"AP04" : "YSR Kadapa",
	"AP05" : "East Godavari",
	"AP06" : "East Godavari",
	"AP07" : "Guntur",
	"AP08" : "Guntur",
	"AP18" : "Krishna",
	"AP21" : "Kurnool",
	"AP26" : "Nellore",
	"AP27" : "Prakasam",
	"AP30" : "Srikakulam",
	"AP31" : "Visakhapatnam",
	"AP32" : "Visakhapatnam",
	"AP33" : "Visakhapatnam",
	"AP34" : "Visakhapatnam",
	"AP35" : "Vizianagaram",
	"AP37" : "West Godavari",
	"AP39" : "Kadapa",
	"WB01" : "Kolkata",
	"WB02" : "Kolkata",
	"WB03" : "Kolkata",
	"WB04" : "Kolkata",
	"WB05" : "Kolkata",
	"WB06" : "Kolkata",
	"WB07" : "Kolkata",
	"WB08" : "Kolkata",
	"WB11" : "Howrah",
	"WB12" : "Howrah",
	"WB13" : "Uluberia",
	"WB14" : "Uluberia",
	"WB15" : "Hoogly",
	"WB16" : "Hoogly",
	"WB17" : "Hooghly",
	"WB18" : "Dankuni",
	"WB19" : "Alipore",
	"WB20" : "Alipore",
	"WB23" : "Barrackpore",
	"WB24" : "Barrackpore",
	"WB25" : "Barasat",
	"WB26" : "Barasat",
	"WB29" : "Tamluk",
	"WB30" : "Tamluk",
	"WB31" : "Contai",
	"WB32" : "Contai",
	"WB33" : "Midnapur",
	"WB34" : "Midnapur",
	"WB36" : "Midnapur",
	"WB37" : "Asansol",
	"WB38" : "Asansol",
	"WB39" : "Durgapur",
	"WB40" : "Durgapur",
	"WB41" : "Burdwan",
	"WB42" : "Burdwan",
	"WB43" : "Kalna",
	"WB44" : "Asansol",
	"WB47" : "Bolpur",
	"WB48" : "Bolpur",
	"WB51" : "Nadia",
	"WB52" : "Nadia",
	"WB53" : "Birbhum",
	"WB54" : "Birbhum",
	"WB55" : "Purulia",
	"WB56" : "Purulia",
	"WB57" : "Murshidabad",
	"WB58" : "Murshidabad",
	"WB59" : "Raiganj",
	"WB60" : "Raiganj",
	"WB61" : "Balurghat",
	"WB62" : "Balurghat",
	"WB63" : "Cooch Behar",
	"WB64" : "Cooch Behar",
	"WB65" : "Malda",
	"WB66" : "Malda",
	"WB67" : "Bankura",
	"WB68" : "Bankura",
	"WB69" : "Alipurduar",
	"WB70" : "Alipurduar",
	"WB71" : "Jalpaiguri",
	"WB72" : "Jalpaiguri",
	"WB73" : "Siliguri",
	"WB74" : "Siliguri",
	"WB76" : "Darjeeling",
	"WB77" : "Darjeeling",
	"WB78" : "Kalimpong",
	"WB79" : "Kalimpong",
	"WB82" : "Raghunathpur",
	"WB85" : "Mathabhanga",
	"WB86" : "Mathabhanga ",
	"WB89" : "Kalyani",
	"WB90" : "Kalyani",
	"WB91" : "Islampur",
	"WB92" : "Islampur",
	"WB93" : "Jahangirpur",
	"WB94" : "Jahangirpur",
	"WB96" : "Baruipur",
	"TN01" : "Chennai",
	"TN02" : "Chennai",
	"TN03" : "Chennai",
	"TN04" : "Chennai",
	"TN05" : "Chennai",
	"TN06" : "Chennai",
	"TN07" : "Chennai",
	"TN09" : "Chennai",
	"TN10" : "Chennai",
	"TN11" : "Chennai",
	"TN12" : "Chennai",
	"TN13" : "Chennai",
	"TN14" : "Chennai",
	"TN15" : "Chennai",
	"TN16" : "Chennai",
	"TN18" : "Chennai",
	"TN19" : "Chengalpattu",
	"TN20" : "Tiruvallur",
	"TN21" : "Kanchipuram",
	"TN22" : "Meenambakkam",
	"TN23" : "Vellore",
	"TN24" : "Krishnagiri",
	"TN25" : "Thiruvannamalai",
	"TN27" : "Salem",
	"TN28" : "Namakkal",
	"TN29" : "Dharmapuri",
	"TN30" : "Salem",
	"TN31" : "Cuddalore",
	"TN32" : "Villupuram",
	"TN33" : "Erode",
	"TN34" : "Thiruchengode",
	"TN36" : "Gobichettipalayam",
	"TN37" : "Coimbatore",
	"TN38" : "Coimbatore",
	"TN39" : "Tiruppur",
	"TN40" : "Mettupalayam",
	"TN41" : "Pollachi",
	"TN42" : "Tiruppur",
	"TN43" : "Udagamandalam",
	"TN45" : "Tiruchirappalli",
	"TN46" : "Perambalur",
	"TN47" : "Karur",
	"TN48" : "Srirangam",
	"TN49" : "Thanjavur",
	"TN50" : "Tiruvarur",
	"TN51" : "Nagapattinam",
	"TN52" : "Sankagiri",
	"TN54" : "Salem",
	"TN55" : "Pudukkottai",
	"TN56" : "Perundurai",
	"TN57" : "Dindigul",
	"TN58" : "Madurai",
	"TN59" : "Madurai",
	"TN60" : "Theni",
	"TN61" : "Ariyalur",
	"TN63" : "Sivagangai",
	"TN64" : "Madurai",
	"TN65" : "Ramanathapuram",
	"TN66" : "Coimbatore",
	"TN67" : "Virudhunagar",
	"TN68" : "Kumbakonam",
	"TN69" : "Thoothukkudi",
	"TN70" : "Hosur",
	"TN72" : "Tirunelveli",
	"TN73" : "Ranipet",
	"TN74" : "Nagercoil",
	"TN75" : "Kanniyakumari",
	"TN76" : "Tenkasi",
	"TN77" : "Attur",
	"TN78" : "Dharapuram",
	"TN79" : "Sankarankovil",
	"TN81" : "Tiruchirappalli",
	"TN82" : "Mayiladuthurai",
	"TN83" : "Tirupathur",
	"TN84" : "Srivilliputhur",
	"TN85" : "Kundrathur",
	"TN86" : "Erode",
	"TN88" : "Namakkal",
	"TN90" : "Salem",
	"TN91" : "Chidambaram",
	"TN92" : "Thiruchendur",
	"TN99" : "Coimbatore",
	"KL01" : "Thiruvananthapuram",
	"KL02" : "Kollam",
	"KL03" : "Pathanamthitta",
	"KL04" : "Alappuzha",
	"KL05" : "Kottayam",
	"KL06" : "Idukki",
	"KL07" : "Ernakulam",
	"KL08" : "Thrissur",
	"KL09" : "Palakkad",
	"KL10" : "Malappuram",
	"KL11" : "Kozhikode",
	"KL12" : "Wayanad",
	"KL13" : "Kannur",
	"KL14" : "Kasaragod",
	"KL16" : "Attingal",
	"KL17" : "Muvattupuzha",
	"KL18" : "Vadakara",
	"KL19" : "Parassala",
	"KL20" : "Neyyattinkara",
	"KL21" : "Nedumangad",
	"KL22" : "Thiruvananthapuram",
	"KL23" : "Karunagapally",
	"KL24" : "Kottarakara",
	"KL25" : "Punalur",
	"KL26" : "Adoor",
	"KL27" : "Thiruvalla",
	"KL28" : "Mallappally",
	"KL29" : "Kayamkulam",
	"KL30" : "Chengannur",
	"KL31" : "Mavelikara",
	"KL32" : "Cherthala",
	"KL33" : "Changanassery",
	"KL34" : "Kanjirappally",
	"KL35" : "Pala",
	"KL36" : "Vaikom",
	"KL37" : "Vandiperiyar",
	"KL38" : "Thodupuzha",
	"KL39" : "Thripunithura",
	"KL40" : "Perumbavoor",
	"KL41" : "Aluva",
	"KL42" : "North Paravur",
	"KL43" : "Mattancherry",
	"KL44" : "Kothamangalam",
	"KL45" : "Irinjalakuda",
	"KL46" : "Guruvayur",
	"KL47" : "Kodungallur",
	"KL48" : "Wadakkancherry",
	"KL49" : "Alathur",
	"KL50" : "Mannarghat",
	"KL51" : "Ottappalam",
	"KL52" : "Pattambi",
	"KL53" : "Perinthalmanna",
	"KL54" : "Ponnani",
	"KL55" : "Tirur",
	"KL56" : "Koyilandi",
	"KL57" : "Koduvally",
	"KL58" : "Thalassery",
	"KL59" : "Thaliparamba",
	"KL60" : "Kanhangad",
	"KL61" : "Kunnathur",
	"KL62" : "Ranni",
	"KL63" : "Angamaly",
	"KL64" : "Chalakkudy",
	"KL65" : "Thirurangadi",
	"KL66" : "Kuttanadu",
	"KL67" : "Uzhavoor",
	"KL68" : "Devikulam",
	"KL69" : "Udumbanchola",
	"KL70" : "Chittoor",
	"KL71" : "Nilambur",
	"KL72" : "Mananthavady",
	"KL73" : "Sulthan Bathery",
	"KL74" : "Kattakkada",
	"KL75" : "Thriprayar",
	"KL76" : "Nanmanda",
	"KL77" : "Perambra",
	"KL78" : "Iritty",
	"KL79" : "Vellarikundu",
	"KL80" : "Varkala",
	"KA01" : "Bengaluru",
	"KA03" : "Bengaluru",
	"KA02" : "Bengaluru",
	"KA04" : "Bengaluru",
	"KA06" : "Tumkur",
	"KA05" : "Bengaluru",
	"KA07" : "Kolar",
	"KA09" : "Mysore",
	"KA08" : "KGF",
	"KA10" : "Chamarajanagar",
	"KA11" : "Mandya",
	"KA13" : "Hassan",
	"KA12" : "Madikeri",
	"KA14" : "Shimoga",
	"KA15" : "Sagar",
	"KA17" : "Davangere",
	"KA16" : "Chitradurga",
	"KA18" : "Chikmagalur",
	"KA19" : "Mangalore",
	"KA21" : "Puttur",
	"KA20" : "Udupi",
	"KA22" : "Belagavi",
	"KA24" : "Bailhongal",
	"KA23" : "Chikkodi",
	"KA27" : "Gadag",
	"KA25" : "Dharwad",
	"KA27" : "Haveri",
	"KA28" : "Bijapur",
	"KA30" : "Karwar",
	"KA29" : "Bagalkote",
	"KA31" : "Sirsi",
	"KA33" : "Yadgir",
	"KA35" : "Hospet",
	"KA34" : "Bellary",
	"KA36" : "Raichur",
	"KA37" : "Koppal",
	"KA38" : "Bidar",
	"KA40" : "Chikkaballapura",
	"KA39" : "Bhalki",
	"KA41" : "Bengaluru",
	"KA43" : "Bengaluru",
	"KA42" : "Bengaluru",
	"KA44" : "Tumakuru",
	"KA46" : "Hassan",
	"KA45" : "Mysore",
	"KA47" : "Uttara Kannada",
	"KA49" : "Belagavi",
	"KA48" : "Bagalkote",
	"KA50" : "Bengaluru",
	"KA52" : "Bengaluru",
	"KA51" : "Bengaluru",
	"KA54" : "Mandya",
	"KA53" : "Bengaluru",
	"KA55" : "Mysore",
	"KA56" : "Basavakalyan",
	"KA59" : "Bengaluru",
	"KA58" : "Bengaluru",
	"KA60" : "Bengaluru",
	"KA61" : "Bengaluru",
	"KA62" : "Dakshina Kannada",
	"KA63" : "Dharwad",
	"KA65" : "Uttara Kannada",
	"KA64" : "Tumakuru",
	"KA66" : "Chikmagalur",
	"KA68" : "Haveri",
	"KA67" : "Chikkaballapur",
	"KA69" : "Belagavi",
	"KA70" : "Dakshina Kannada",
	"TG01" : "Adilabad",
	"TG02" : "Karimnagar",
	"TG03" : "Warangal",
	"TG04" : "Khammam",
	"TG05" : "Nalgonda",
	"TG06" : "Mahbubnagar",
	"TG07" : "Ranga Reddy",
	"TG08" : "Medchal Malkajgiri",
	"TG09" : "Hyderabad",
	"TG10" : "Hyderabad",
	"TG11" : "Hyderabad",
	"TG12" : "Hyderabad",
	"TG13" : "Hyderabad",
	"TG15" : "Sangareddy",
	"TG16" : "Nizamabad",
	"TG17" : "Kamareddy",
	"TG18" : "Nirmal",
	"TG19" : "Mancherial",
	"TG20" : "Kumuram Bheem Asifabad",
	"TG21" : "Jagitial",
	"TG22" : "Peddapalli",
	"TG23" : "Rajanna Sircilla",
	"TG24" : "Warangal",
	"TG25" : "Jayashankar",
	"TG26" : "Mahabubabad",
	"TG27" : "Jangoan",
	"TG28" : "Bhadradri Kothagudem",
	"TG29" : "Suryapet",
	"TG30" : "Yadadri Bhuvanagiri",
	"TG31" : "Nagarkurnool",
	"TG32" : "Wanaparthy",
	"TG33" : "Jogulamba Gadwal",
	"TG34" : "Vikarabad",
	"TG35" : "Medak",
	"TG36" : "Siddipet",
	"GA01" : "North Goa",
	"GA02" : "South Goa",
	"GA03" : "North Goa",
	"GA04" : "North Goa",
	"GA05" : "South Goa",
	"GA06" : "South Goa",
	"GA07" : "North Goa",
	"GA08" : "South Goa",
	"GA09" : "South Goa",
	"GA10" : "South Goa",
	"GA11" : "North Goa",
	"GA12" : "South Goa",
	"GJ01" : "Ahmedabad",
	"GJ02" : "Mehsana",
	"GJ03" : "Rajkot",
	"GJ04" : "Bhavnagar",
	"GJ05" : "Surat",
	"GJ06" : "Vadodara",
	"GJ07" : "Kheda",
	"GJ08" : "Banaskantha",
	"GJ09" : "Sabarkantha",
	"GJ10" : "Jamnagar",
	"GJ11" : "Junagadh",
	"GJ12" : "Kutch",
	"GJ13" : "Surendranagar",
	"GJ14" : "Amreli",
	"GJ15" : "Valsad",
	"GJ16" : "Bharuch",
	"GJ17" : "Panchmahal",
	"GJ18" : "Gandhinagar",
	"GJ19" : "Bardoli",
	"GJ20" : "Dahod",
	"GJ21" : "Navsari",
	"GJ22" : "Narmada",
	"GJ23" : "Anand",
	"GJ24" : "Patan",
	"GJ25" : "Porbandar",
	"GJ26" : "Vyara",
	"GJ27" : "Ahmedabad",
	"GJ30" : "Aahwa",
	"GJ31" : "Modasa",
	"GJ32" : "Veraval",
	"GJ33" : "Botad",
	"GJ34" : "Chhota Udaipur",
	"GJ35" : "Lunavada",
	"GJ36" : "Morbi",
	"GJ37" : "Khambhaliya",
	"GJ38" : "Bavla",
	"UP11" : "Saharanpur",
	"UP12" : "Muzaffarnagar",
	"UP13" : "Bulandshahr",
	"UP14" : "Ghaziabad",
	"UP15" : "Meerut",
	"UP16" : "Noida",
	"UP17" : "Bagpat",
	"UP19" : "Shamli",
	"UP20" : "Bijnor",
	"UP21" : "Moradabad",
	"UP22" : "Rampur",
	"UP23" : "Amroha",
	"UP24" : "Badaun",
	"UP25" : "Bareilly",
	"UP26" : "Pilibhit",
	"UP27" : "Shahjahanpur",
	"UP30" : "Hardoi",
	"UP31" : "Lakhimpur Kheri",
	"UP32" : "Lucknow",
	"UP33" : "Rae Bareli",
	"UP34" : "Sitapur",
	"UP35" : "Unnao",
	"UP36" : "Amethi",
	"UP37" : "Hapur",
	"UP38" : "Sambhal",
	"UP40" : "Bahraich",
	"UP41" : "Barabanki",
	"UP42" : "Faizabad",
	"UP43" : "Gonda",
	"UP44" : "Sultanpur",
	"UP45" : "Ambedkar Nagar",
	"UP46" : "Shrawasti",
	"UP47" : "Balrampur",
	"UP50" : "Azamgarh",
	"UP51" : "Basti",
	"UP52" : "Deoria",
	"UP53" : "Gorakhpur",
	"UP54" : "Mau",
	"UP55" : "Siddharthnagar",
	"UP56" : "Mahrajganj",
	"UP57" : "Padrauna",
	"UP58" : "Sant Kabir Nagar",
	"UP60" : "Ballia",
	"UP61" : "Ghazipur",
	"UP62" : "Jaunpur",
	"UP63" : "Mirzapur",
	"UP64" : "Sonbhadra",
	"UP65" : "Varanasi",
	"UP66" : "Sant Ravidas Nagar",
	"UP67" : "Chandauli",
	"UP70" : "Prayagraj",
	"UP71" : "Fatehpur",
	"UP72" : "Pratapgarh",
	"UP73" : "Kaushambi",
	"UP74" : "Kannauj",
	"UP75" : "Etawah",
	"UP76" : "Farrukhabad",
	"UP77" : "Kanpur Dehat",
	"UP78" : "Kanpur Nagar",
	"UP79" : "Auraiya",
	"UP80" : "Agra",
	"UP81" : "Aligarh",
	"UP82" : "Etah",
	"UP83" : "Firozabad",
	"UP84" : "Mainpuri",
	"UP85" : "Mathura",
	"UP86" : "Mahamaya Nagar",
	"UP87" : "Kanshiram Nagar",
	"UP90" : "Banda",
	"UP91" : "Hamirpur",
	"UP92" : "Jalaun",
	"UP93" : "Jhansi",
	"UP94" : "Lalitpur",
	"UP95" : "Mahoba",
	"UP96" : "Chitrakoot Dham",
	"MP04" : "Bhopal",
	"MP05" : "Hoshangabad",
	"MP06" : "Morena",
	"MP07" : "Gwalior",
	"MP08" : "Guna",
	"MP09" : "Indore",
	"MP10" : "Khargone",
	"MP11" : "Dhar",
	"MP12" : "Khandwa",
	"MP13" : "Ujjain",
	"MP14" : "Mandsaur",
	"MP15" : "Sagar",
	"MP16" : "Chhatarpur",
	"MP17" : "Rewa",
	"MP18" : "Shahdol",
	"MP19" : "Satna",
	"MP20" : "Jabalpur",
	"MP21" : "Katni",
	"MP22" : "Seoni",
	"MP23" : "Raipur",
	"MP24" : "Durg",
	"MP25" : "Jagdalpur",
	"MP26" : "Bilaspur",
	"MP27" : "Ambikapur",
	"MP28" : "Chhindwara",
	"MP29" : "Rajnandgaon",
	"MP30" : "Bhind",
	"MP31" : "Sheopur",
	"MP32" : "Datia",
	"MP33" : "Shivpuri",
	"MP34" : "Damoh",
	"MP35" : "Panna",
	"MP36" : "Tikamgarh",
	"MP37" : "Sehore",
	"MP38" : "Raisen",
	"MP39" : "Rajgarh",
	"MP40" : "Vidisha",
	"MP41" : "Dewas",
	"MP42" : "Shajapur",
	"MP43" : "Ratlam",
	"MP44" : "Neemuch",
	"MP45" : "Jhabua",
	"MP46" : "Badwani",
	"MP47" : "Harda",
	"MP48" : "Betul",
	"MP49" : "Narsinghpur",
	"MP50" : "Balaghat",
	"MP51" : "Mandla",
	"MP52" : "Dindori",
	"MP53" : "Sidhi",
	"MP54" : "Umariya",
	"MP55" : "Bagli",
	"MP65" : "Anuppur",
	"MP66" : "Singrauli",
	"MP67" : "Ashoknagar",
	"MP68" : "Burhanpur",
	"MP69" : "Alirajpur",
	"MP70" : "Agar Malwa",
	"BR01" : "Patna",
	"BR02" : "Gaya",
	"BR03" : "Bhojpur",
	"BR04" : "Chapra",
	"BR05" : "Motihari",
	"BR06" : "Muzaffarpur",
	"BR07" : "Darbhanga",
	"BR08" : "Munger",
	"BR09" : "Begusarai",
	"BR10" : "Bhagalpur",
	"BR11" : "Purnia",
	"BR19" : "Saharsa",
	"BR21" : "Nalanda",
	"BR22" : "Bettiah",
	"BR24" : "Dehri",
	"BR25" : "Jehanabad",
	"BR26" : "Aurangabad",
	"BR27" : "Nawada",
	"BR28" : "Gopalganj",
	"BR29" : "Siwan",
	"BR30" : "Sitamarhi",
	"BR31" : "Vaishali",
	"BR32" : "Madhubani",
	"BR33" : "Samastipur",
	"BR34" : "Khagaria",
	"BR37" : "Kishanganj",
	"BR38" : "Araria",
	"BR39" : "Katihar",
	"BR43" : "Madhepura",
	"BR44" : "Buxar",
	"BR45" : "Bhabua",
	"BR46" : "Jamui",
	"BR50" : "Supaul",
	"BR51" : "Banka",
	"BR52" : "Sheikhpura",
	"BR53" : "Lakhisarai",
	"BR55" : "Sheohar",
	"BR56" : "Arwal",
	"BR57" : "Rohtas",
	"PY01" : "Puducherry",
	"PY02" : "Karaikal",
	"PY03" : "Mahe",
	"PY04" : "Yanam",
	"PY05" : "Oulgaret",
	"JH01" : "Ranchi",
	"JH02" : "Hazaribagh",
	"JH03" : "Daltonganj",
	"JH04" : "Dumka",
	"JH05" : "Jamshedpur",
	"JH06" : "Chaibasa",
	"JH07" : "Gumla",
	"JH08" : "Lohardaga",
	"JH09" : "Bokaro",
	"JH10" : "Dhanbad",
	"JH11" : "Giridih",
	"JH12" : "Koderma",
	"JH13" : "Chatra",
	"JH14" : "Garhwa",
	"JH15" : "Deoghar",
	"JH16" : "Pakur",
	"JH17" : "Godda",
	"JH18" : "Sahibganj",
	"JH19" : "Latehar",
	"JH20" : "Simdega",
	"JH21" : "Jamtara",
	"JH22" : "Saraikela Kharsawan",
	"JH23" : "Khunti",
	"JH24" : "Ramgarh",
	"DL01" : "North Delhi",
	"DL02" : "New Delhi",
	"DL03" : "South Delhi",
	"DL04" : "West Delhi",
	"DL05" : "North East Delhi",
	"DL06" : "Central Delhi",
	"DL07" : "East Delhi",
	"DL08" : "North West Delhi",
	"DL09" : "South West Delhi",
	"DL10" : "West Delhi",
	"DL11" : "North West Delhi",
	"DL12" : "South West Delhi",
	"DL13" : "Shahdara",
	"DD02" : "Diu",
	"DD03" : "Daman",
	"DN09" : "Dadra and Nagar Haveli",
	"CH01" : "Chandigarh",
	"CH03" : "Chandigarh",
	"CH04" : "Chandigarh",
	"AN01" : "South Andaman",
	"AN02" : "North and Middle Andaman",
	"TR01" : "Agartala",
	"TR02" : "Kailashahar",
	"TR03" : "Udaipura",
	"TR04" : "Dharamanagar",
	"TR05" : "Ambassa",
	"SK01" : "Gangtok",
	"SK02" : "Gyalshing",
	"SK03" : "Mangan",
	"SK04" : "Jorethang",
	"RJ01" : "Ajmer",
	"RJ02" : "Alwar",
	"RJ03" : "Banswara",
	"RJ04" : "Barmer",
	"RJ05" : "Bharatpur",
	"RJ06" : "Bhilwara",
	"RJ07" : "Bikaner",
	"RJ08" : "Bundi",
	"RJ09" : "Chittorgarh",
	"RJ10" : "Churu",
	"RJ11" : "Dholpur",
	"RJ12" : "Dungarpur",
	"RJ13" : "Sri Ganganagar",
	"RJ14" : "Jaipur",
	"RJ15" : "Jaisalmer",
	"RJ16" : "Jalore",
	"RJ17" : "Jhalawar",
	"RJ18" : "Jhunjhunu",
	"RJ19" : "Jodhpur",
	"RJ20" : "Kota",
	"RJ21" : "Nagaur",
	"RJ22" : "Pali",
	"RJ23" : "Sikar",
	"RJ24" : "Sirohi",
	"RJ25" : "Sawai Madhopur",
	"RJ26" : "Tonk",
	"RJ27" : "Udaipur",
	"RJ28" : "Baran",
	"RJ29" : "Dausa",
	"RJ30" : "Rajsamand",
	"RJ31" : "Hanumangarh",
	"RJ32" : "Jaipur",
	"RJ33" : "Kota",
	"RJ34" : "Karauli",
	"RJ35" : "Pratapgarh",
	"RJ36" : "Ajmer",
	"RJ37" : "Nagaur",
	"RJ38" : "Sirohi",
	"RJ39" : "Barmer",
	"RJ40" : "Alwar",
	"RJ41" : "Jaipur",
	"RJ42" : "Ajmer",
	"RJ43" : "Jodhpur",
	"RJ44" : "Churu",
	"RJ45" : "Jaipur",
	"RJ46" : "Jalore",
	"RJ47" : "Jaipur",
	"RJ48" : "Ajmer",
	"RJ49" : "Hanumangrah",
	"RJ50" : "Bikaner",
	"RJ51" : "Bhilwara",
	"RJ52" : "Jaipur",
	"PB02" : "Amritsar",
	"PB03" : "Bathinda",
	"PB04" : "Faridkot",
	"PB05" : "Ferozepur",
	"PB06" : "Gurdaspur",
	"PB07" : "Hoshiarpur",
	"PB08" : "Jalandhar",
	"PB09" : "Kapurthala",
	"PB10" : "Ludhiana",
	"PB11" : "Patiala",
	"PB12" : "Ropar",
	"PB13" : "Sangrur",
	"PB14" : "Ajnala",
	"PB15" : "Abohar",
	"PB16" : "Anandpur Sahib",
	"PB17" : "Baba Bakala",
	"PB18" : "Batala",
	"PB19" : "Barnala",
	"PB20" : "Balachaur",
	"PB21" : "Dasuya",
	"PB22" : "Fazilka",
	"PB23" : "Fatehgarh Sahib",
	"PB24" : "Garhshankar",
	"PB25" : "Jagraon",
	"PB26" : "Khanna",
	"PB27" : "Kharar",
	"PB28" : "Malerkotla",
	"PB29" : "Moga",
	"PB30" : "Sri Muktsar Sahib",
	"PB31" : "Mansa",
	"PB32" : "Nawanshahr",
	"PB33" : "Nakodar",
	"PB34" : "Patiala",
	"PB35" : "Pathankot",
	"PB36" : "Phagwara",
	"PB37" : "Phillaur",
	"PB38" : "Patti",
	"PB39" : "Patiala",
	"PB40" : "Rampura Phul",
	"PB41" : "Sultanpur Lodhi",
	"PB42" : "Patiala",
	"PB43" : "Samrala",
	"PB44" : "Sunam",
	"PB45" : "Talwandi Sabo",
	"PB46" : "Tarn Taran",
	"PB47" : "Zira",
	"PB48" : "Amloh",
	"PB49" : "Khamano",
	"PB50" : "Budhlada",
	"PB51" : "Jhunir",
	"PB52" : "Bassi Pathana",
	"PB53" : "Malout",
	"PB54" : "Mukerian",
	"PB55" : "Payal",
	"PB56" : "Raikot",
	"PB57" : "Bhulath",
	"PB58" : "Dera Baba Nanak",
	"PB59" : "Dhuri",
	"PB60" : "Gidderbaha",
	"PB61" : "Jalalabad",
	"PB62" : "Jaitu",
	"PB63" : "Khadoor Sahib",
	"PB64" : "Moonak",
	"PB65" : "Mohali",
	"PB66" : "Nihal Singh Wala",
	"PB67" : "Shahkot",
	"PB68" : "Dhar Kalan",
	"PB69" : "Bagha Purana",
	"PB70" : "Dera Bassi",
	"PB71" : "Chamkaur Sahib",
	"PB72" : "Patiala",
	"PB73" : "Tappa Mandi",
	"PB74" : "Nangal",
	"PB75" : "Lehra",
	"PB76" : "Ahmedgarh",
	"PB77" : "Guru Har Sahai",
	"OR01" : "Balasore",
	"OR02" : "Bhubaneswar",
	"OR03" : "Bolangir",
	"OR04" : "Chandikhol",
	"OR05" : "Cuttack",
	"OR06" : "Dhenkanal",
	"OR07" : "Ganjam",
	"OR08" : "Kalahandi",
	"OR09" : "Keonjhar",
	"OR10" : "Koraput",
	"OR11" : "Mayurbhanj",
	"OR12" : "Phulabani Khandamal",
	"OR13" : "Puri",
	"OR14" : "Rourkela",
	"OR15" : "Sambalpur",
	"OR16" : "Sundergarh",
	"OR17" : "Baragarh",
	"OR18" : "Rayagada",
	"OR19" : "Angul",
	"OR20" : "Gajapati",
	"OR21" : "Jagatsinghpur",
	"OR22" : "Bhadrak",
	"OR23" : "Jharsuguda",
	"OR24" : "Nabarangpur",
	"OR25" : "Nayagarh",
	"OR26" : "Nuapada",
	"OR27" : "Boudh",
	"OR28" : "Debagarh",
	"OR29" : "Kendrapara",
	"OR30" : "Malkangiri",
	"OR31" : "Sonepur",
	"OR32" : "Bhanjanagar",
	"OR33" : "Bhubaneswar",
	"OR34" : "Jajpur",
	"OR35" : "Talcher",
	"MZ01" : "Aizawl",
	"MZ02" : "Lunglei",
	"MZ03" : "Saiha",
	"MZ04" : "Champhai",
	"MZ05" : "Kolasib",
	"MZ06" : "Serchhip",
	"MZ07" : "Lawngtlai",
	"MZ08" : "Mamit",
	"ML04" : "Jaintia Hills",
	"ML05" : "Shillong",
	"ML06" : "West Khasi Hills",
	"ML07" : "East Garo Hills",
	"ML08" : "West Garo Hills",
	"ML09" : "South Garo Hills",
	"ML10" : "Ri-Bhoi",
	"ML11" : "East Jaintia Hils",
	"ML12" : "East Khasi Hills",
	"ML13" : "North Garo Hills",
	"ML14" : "West Garo Hills",
	"MN01" : "Imphal West",
	"MN02" : "Churachandpur",
	"MN03" : "Kangpokpi",
	"MN04" : "Thoubal",
	"MN05" : "Bishnupur",
	"MN06" : "Imphal East",
	"MN07" : "Ukhrul",
	"JK01" : "Srinagar",
	"JK02" : "Jammu",
	"JK03" : "Anantnag",
	"JK04" : "Budgam",
	"JK05" : "Baramulla",
	"JK06" : "Doda",
	"JK08" : "Kathua",
	"JK09" : "Kupwara",
	"JK11" : "Rajouri",
	"JK12" : "Poonch",
	"JK13" : "Pulwama",
	"JK14" : "Udhampur",
	"JK15" : "Bandipora",
	"JK16" : "Ganderbal",
	"JK17" : "Kishtwar",
	"JK18" : "Kulgam",
	"JK19" : "Ramban",
	"JK20" : "Reasi",
	"JK21" : "Samba",
	"JK22" : "Shopian",
	"HP03" : "Shimla",
	"HP04" : "Dharamsala",
	"HP05" : "Mandi",
	"HP06" : "Rampur",
	"HP07" : "Shimla",
	"HP08" : "Chaupal",
	"HP09" : "Theog",
	"HP10" : "Rohru",
	"HP11" : "Arki",
	"HP12" : "Nalagarh",
	"HP13" : "Kandaghat",
	"HP14" : "Solan",
	"HP15" : "Parwanoo",
	"HP16" : "Rajgarh",
	"HP17" : "Paonta Sahib",
	"HP18" : "Nahan",
	"HP19" : "Amb",
	"HP20" : "Una",
	"HP21" : "Barsar",
	"HP22" : "Hamirpur",
	"HP23" : "Ghumarwin",
	"HP24" : "Bilaspur",
	"HP25" : "Kalpa",
	"HP26" : "Nichar",
	"HP27" : "Poo",
	"HP28" : "Sarkaghat",
	"HP29" : "Jogindernagar",
	"HP30" : "Karsog",
	"HP31" : "Sundernagar",
	"HP32" : "Mandi",
	"HP33" : "Mandi",
	"HP34" : "Kullu",
	"HP35" : "Anni",
	"HP36" : "Dehra",
	"HP37" : "Palampur",
	"HP38" : "Nurpur",
	"HP39" : "Dharamshala",
	"HP40" : "Kangra",
	"HP41" : "Kaza",
	"HP42" : "Keylong",
	"HP43" : "Udaipur",
	"HP44" : "Churah",
	"HP45" : "Pangi",
	"HP46" : "Bharmour",
	"HP47" : "Dalhousie",
	"HP48" : "Chamba",
	"HP49" : "Banjar",
	"HP50" : "Shimla",
	"HP51" : "Shimla",
	"HP52" : "Shimla",
	"HP53" : "Baijnath",
	"HP54" : "Jawali",
	"HP55" : "Hamirpur",
	"HP56" : "Jaisinghpur",
	"HP57" : "Chowari",
	"HP58" : "Manali",
	"HP62" : "Shimla",
	"HP63" : "Shimla",
	"HP64" : "Solan",
	"HP65" : "Mandi",
	"HP66" : "Kullu",
	"HP67" : "Hamirpur",
	"HP68" : "Dharmsala",
	"HP69" : "Bilaspur",
	"HP71" : "Nahan",
	"HP72" : "Una",
	"HP73" : "Chamba",
	"HP74" : "Bhoranj",
	"HP76" : "Paddhar",
	"HP77" : "Dodra Kawar",
	"HP78" : "Bangana",
	"HP79" : "Sangrah",
	"HP80" : "Haroli",
	"HP81" : "Salooni",
	"HP82" : "Mandi",
	"HP83" : "Jawalaji",
	"HP84" : "Sujanpur",
	"HP85" : "Shillai",
	"HP86" : "Dharampur",
	"CT04" : "Raipur",
	"CT05" : "Dhamtari",
	"CT06" : "Mahasamund",
	"CT07" : "Durg",
	"CT08" : "Rajnandgaon",
	"CT09" : "Kawardha",
	"CT10" : "Bilaspur",
	"CT11" : "Janjgir-Champa",
	"CT12" : "Korba",
	"CT13" : "Raigarh",
	"CT14" : "Jashpur",
	"CT15" : "Sarguja",
	"CT16" : "Koriya",
	"CT17" : "Jagdalpur",
	"CT18" : "Dantewada",
	"CT19" : "Kanker",
	"CT20" : "Bijapur",
	"CT21" : "Narayanpur",
	"CT22" : "Baloda Bazar",
	"CT23" : "Gariaband",
	"CT24" : "Balod",
	"CT25" : "Bemetara",
	"CT26" : "Sukma",
	"CT27" : "Kondagaon",
	"CT28" : "Mungeli",
	"CT29" : "Surajpur",
	"CT30" : "Balrampur",
	"AR01" : "Guwahati",
	"AR02" : "Nagaon",
	"AR03" : "Jorhat",
	"AR04" : "Sibsagar",
	"AR05" : "Golaghat",
	"AR06" : "Dibrugarh",
	"AR07" : "Lakhimpur district",
	"AR08" : "Dima Hasao",
	"AR09" : "Karbi Anglong",
	"AR10" : "Karimganj",
	"AR11" : "Lohit",
	"AR12" : "Sonitpur",
	"AR13" : "Darrang",
	"AR14" : "Nalbari",
	"AR15" : "Barpeta",
	"AR16" : "Kokrajhar",
	"AR17" : "Dhubri",
	"AR18" : "Goalpara",
	"AR19" : "Bongaigaon",
	"AR21" : "Marigaon",
	"AR22" : "Dhemaji",
	"AR23" : "Tinsukia",
	"AR24" : "Hailakandi",
	"AR25" : "Kamrup Rural",
	"AR26" : "Chirang",
	"AR27" : "Udalguri",
	"AR28" : "Baksa",
	}
	return dists[passing]
